apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  # - pvc.yaml  # Uncomment if you need to create a new PVC

commonLabels:
  app: comfyui-worker

namespace: default
